name: Validate
permissions: {}
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  validate:
    uses: grafana/xk6/.github/workflows/extension-validate.yml@1556f094f3883e37ebff04b967fddac30681c466 # v1.4.1
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      go-version: "1.25.x"
      go-versions: '["1.25.x"]'
      golangci-lint-version: "v2.7.1"
      platforms: '["ubuntu-latest","windows-latest","macos-latest"]'
      k6-versions: '["v2.0.0"]'
      xk6-version: "1.4.1"
      xk6-test-pattern: "test/*.test.{j,t}s"
